AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: serverless1/
      Handler: app.lambda_handler
      Runtime: python3.11
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events: s3:ObjectCreated:*

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: london-test-data


